In [1]:
import numpy as np

In [2]:
w = 20

In [3]:
h = 30

In [30]:
A = np.array([1,3.5,3,4])
# color 255,255,255,255

In [32]:
B = np.array([2,0,0,2])
# color 255,255,255,255

In [31]:
C = np.array([-1,-2,-3,4])
# color 0,0,0,255

In [33]:
def convert_3D_to_2D(point):
    x = (point[0]/point[3] + 1) * w / 2
    y = (point[1]/point[3] + 1) * h / 2
    return np.array([x,y])

In [34]:
A2, B2, C2 = convert_3D_to_2D(A),convert_3D_to_2D(B), convert_3D_to_2D(C)

In [35]:
A2,B2,C2

(array([12.5  , 28.125]), array([20., 15.]), array([7.5, 7.5]))

In [42]:
# find smallest y, point B
# take ceiling of y coordinate
s_AC = (A2-C2)/(A2[1]-C2[1])
s_AC

array([0.24242424, 1.        ])

In [43]:
s_AC * 0.5 + C2

array([7.62121212, 8.        ])

In [44]:
s_BC = (C2-B2)/(C2[1]-B2[1])
s_BC

array([1.66666667, 1.        ])

In [46]:
s_BC * 0.5 + C2

array([8.33333333, 8.        ])

In [48]:
(255-0)/(C2[1]-B2[1])*0.5 + 255

238.0